def render_html_page(title: str, body_content: list[str]) -> str:
    """
    Takes a title and a list of HTML snippets and generates a full HTML page.
    """
    body_str = "\n".join(body_content)

    html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: sans-serif; line-height: 1.6; padding: 2em; max-width: 800px; margin: auto; }}
        img {{ max-width: 100%; height: auto; }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
    </header>
    <main>
        {body_str}
    </main>
    <footer>
        <p><br/>---<br/>Generated by mWEB & PocketFlow</p>
    </footer>
</body>
</html>
"""
    return html_template

if __name__ == "__main__":
    print("Testing renderer.py...")
    test_title = "My Test Page"
    test_body = [
        "<p>This is the first paragraph.</p>",
        '<img src="https://via.placeholder.com/400x100" alt="banner">',
        "<p>This is the second paragraph.</p>"
    ]

    generated_html = render_html_page(test_title, test_body)

    print("\\n--- Generated HTML ---")
    print(generated_html)
    print("----------------------\\n")

    # Save to a test file
    with open("test_render.html", "w") as f:
        f.write(generated_html)
    print("Saved to test_render.html")
