from .flow import create_website_flow

def main():
    """
    Main function to run a test of the website generation flow.
    """
    # 1. Define a sample shared store, mimicking frontend input.
    shared_data = {
        "config": {
            "title": "My Test Website"
        },
        "components": {
            "c1_intro": {
                "type": "text",
                "content": "Welcome to mWEB, an AI-powered website builder!"
            },
            "c2_logo": {
                "type": "image",
                "src": "https://raw.githubusercontent.com/The-Pocket/.github/main/assets/title.png",
                "alt": "PocketFlow Logo"
            },
            "c3_body": {
                "type": "text",
                "content": "This website was generated by a PocketFlow graph."
            },
            "c4_welcome": {
                "type": "ai_text",
                "prompt": "Generate a welcome message for our new website."
            }
        },
        "rendered_html": [] # This will be populated by the MergeNode
    }

    # 2. Create the website generation flow.
    website_flow = create_website_flow()

    # 3. Run the flow with the sample data.
    print("--- Running Website Flow ---")
    website_flow.run(shared_data)
    print("--- Flow Execution Complete ---")

    # 4. Print the final rendered HTML.
    print("\n--- Generated HTML Snippets ---")
    for i, html_snippet in enumerate(shared_data["rendered_html"]):
        print(f"{i+1}: {html_snippet}")
    print("-----------------------------\n")

if __name__ == "__main__":
    main()
